version: '3.8'

services:
  frontend:
    command: npm run start:debug
    ports:
      - "9229:9229"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:rw
      - /app/node_modules
