name: Automated Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Check for dependency updates
      run: |
        npm install -g npm-check-updates
        ncu -u --target minor
        
        # Check if package.json was modified
        if git diff --quiet package.json; then
          echo "No dependency updates available"
          echo "UPDATES_AVAILABLE=false" >> $GITHUB_ENV
        else
          echo "Dependency updates found"
          echo "UPDATES_AVAILABLE=true" >> $GITHUB_ENV
          
          # Create summary of changes
          echo "## Dependency Updates" > update_summary.md
          echo "" >> update_summary.md
          echo "The following dependencies have been updated:" >> update_summary.md
          echo "" >> update_summary.md
          git diff package.json >> update_summary.md
        fi
    
    - name: Install updated dependencies
      if: env.UPDATES_AVAILABLE == 'true'
      run: npm install
    
    - name: Run tests with updated dependencies
      if: env.UPDATES_AVAILABLE == 'true'
      run: |
        npm test || echo "Tests completed with exit code $?"
        
        # Check if tests passed
        if npm test; then
          echo "TESTS_PASSED=true" >> $GITHUB_ENV
        else
          echo "TESTS_PASSED=false" >> $GITHUB_ENV
        fi
    
    - name: Run security audit
      if: env.UPDATES_AVAILABLE == 'true'
      run: |
        npm audit --audit-level=moderate > audit_results.txt 2>&1 || true
        
        # Check audit results
        if npm audit --audit-level=high; then
          echo "AUDIT_PASSED=true" >> $GITHUB_ENV
        else
          echo "AUDIT_PASSED=false" >> $GITHUB_ENV
          echo "## Security Audit Issues" >> update_summary.md
          echo "" >> update_summary.md
          cat audit_results.txt >> update_summary.md
        fi
    
    - name: Create Pull Request
      if: env.UPDATES_AVAILABLE == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: automated dependency updates'
        title: '🤖 Automated Dependency Updates'
        body-path: update_summary.md
        branch: automated-dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          ${{ env.TESTS_PASSED == 'true' && 'tests-passing' || 'tests-failing' }}
          ${{ env.AUDIT_PASSED == 'true' && 'security-clean' || 'security-issues' }}
    
    - name: Auto-merge if safe
      if: env.UPDATES_AVAILABLE == 'true' && env.TESTS_PASSED == 'true' && env.AUDIT_PASSED == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          
          // Find the PR created by the previous step
          const { data: prs } = await github.rest.pulls.list({
            owner,
            repo,
            head: `${owner}:automated-dependency-updates`,
            state: 'open'
          });
          
          if (prs.length > 0) {
            const pr = prs[0];
            
            // Auto-approve the PR
            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number: pr.number,
              event: 'APPROVE',
              body: '✅ Auto-approved: All tests pass and no security issues detected.'
            });
            
            // Enable auto-merge
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pr.number,
              commit_title: 'chore: automated dependency updates',
              merge_method: 'squash'
            });
            
            console.log(`Auto-merged PR #${pr.number}`);
          }

  security-scan:
    runs-on: ubuntu-latest
    needs: update-dependencies
    if: always()
    steps:
    - uses: actions/checkout@v4
    
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high